wandb_version: 1

DBG:
  desc: null
  value: false
OUTPUT_DIR:
  desc: null
  value: out/seed32/CUB/sup_vitti16_imagenet21k/lr0.25_wd0.001/run1
RUN_N_TIMES:
  desc: null
  value: 1
CUDNN_BENCHMARK:
  desc: null
  value: false
NUM_GPUS:
  desc: null
  value: 1
NUM_SHARDS:
  desc: null
  value: 1
SEED:
  desc: null
  value: 32
MODEL:
  desc: null
  value:
    TRANSFER_TYPE: prompt
    WEIGHT_PATH: ''
    SAVE_CKPT: false
    MODEL_ROOT: backbones
    TYPE: vit
    MLP_NUM: 0
    LINEAR:
      MLP_SIZES: []
      DROPOUT: 0.1
    PROMPT:
      NUM_TOKENS: 10
      LOCATION: prepend
      INITIATION: random
      CLSEMB_FOLDER: ''
      CLSEMB_PATH: ''
      PROJECT: -1
      DEEP: false
      NUM_DEEP_LAYERS: null
      REVERSE_DEEP: false
      DEEP_SHARED: false
      FORWARD_DEEP_NOEXPAND: false
      VIT_POOL_TYPE: original
      DROPOUT: 0.0
      SAVE_FOR_EACH_EPOCH: false
    ADAPTER:
      REDUCATION_FACTOR: 8
      STYLE: Pfeiffer
SOLVER:
  desc: null
  value:
    LOSS: softmax
    LOSS_ALPHA: 0.01
    OPTIMIZER: sgd
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.001
    WEIGHT_DECAY_BIAS: 0
    PATIENCE: 300
    SCHEDULER: cosine
    BASE_LR: 0.25
    BIAS_MULTIPLIER: 1.0
    WARMUP_EPOCH: 10
    TOTAL_EPOCH: 5
    LOG_EVERY_N: 100
    DBG_TRAINABLE: false
DATA:
  desc: null
  value:
    NAME: CUB
    DATAPATH: datasets/CUB_200_2011
    FEATURE: sup_vitti16_imagenet21k
    PERCENTAGE: 1.0
    NUMBER_CLASSES: 200
    MULTILABEL: false
    CLASS_WEIGHTS_TYPE: none
    CROPSIZE: 224
    NO_TEST: false
    BATCH_SIZE: 64
    NUM_WORKERS: 4
    PIN_MEMORY: true
DIST_BACKEND:
  desc: null
  value: nccl
DIST_INIT_PATH:
  desc: null
  value: env://
DIST_INIT_FILE:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712427709.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
